#!/usr/bin/env bun
/**
 * Build the release artifacts: one self-contained harv per platform (ADR 0007).
 *
 * Everything a released harv needs is decided here and frozen into the binary —
 * its own version, the pinned mise, and that mise's checksum — so the installed
 * tool never has to find a file to know what it is. Three consequences worth
 * knowing about:
 *
 * 1. The entry point is generated. Embedding a file in a Bun executable takes
 *    `import x from "./f" with { type: "file" }`, which plain Node refuses to
 *    parse, and the dev loop (`node bin/harv.ts`) is worth more than the tidiness
 *    of a hand-written entry point. So the Bun-only syntax lives in generated
 *    code under `build/`, and `src/` stays Node-runnable.
 *
 * 2. The version arrives via `--define`, not from package.json. The git tag is
 *    the version; a build with no tag says `0.0.0-dev` and means it.
 *
 * 3. Cross-compilation is Bun's, so every platform builds from one machine and
 *    CI needs no runner matrix to produce artifacts — only to install them.
 *
 * Run:  bun scripts/build.ts --version 0.1.0 --all
 *       bun scripts/build.ts                          # this platform, 0.0.0-dev
 */

import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";

import { PLATFORMS, bunTarget, currentPlatform, isPlatform } from "../src/platform.ts";
import type { Platform } from "../src/platform.ts";
import { DEV_VERSION } from "../src/version.ts";
import { readLock, sha256, vendor, vendoredMisePath } from "./vendor-mise.ts";
import type { Lock } from "./vendor-mise.ts";

const REPO_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const BUILD_DIR = join(REPO_ROOT, "build");
const REPO = "bonyadnouri/harvenv";

export interface Artifact {
  platform: Platform;
  tarball: string;
  sha256: string;
  binaryBytes: number;
  tarballBytes: number;
}

// ---------------------------------------------------------------------------
// The generated entry point
// ---------------------------------------------------------------------------

/**
 * `setEmbeddedMise` before `run`, and both after the asset import — the whole
 * reason this file is generated rather than imported. It is written per
 * platform because the file it embeds differs per platform while its own path
 * must stay a static string the bundler can see.
 */
function entryPointSource(platformDir: string): string {
  const src = (name: string) => relative(platformDir, join(REPO_ROOT, "src", name)).replaceAll("\\", "/");
  return `// Generated by scripts/build.ts. Not committed, not edited.
import misePath from "./mise.gz" with { type: "file" };
import { setEmbeddedMise } from "${src("mise.ts")}";
import { defaultDeps, run } from "${src("cli.ts")}";

setEmbeddedMise(misePath);
process.exitCode = await run(process.argv.slice(2), defaultDeps());
`;
}

// ---------------------------------------------------------------------------
// Building one platform
// ---------------------------------------------------------------------------

/** The bun to build with: our own interpreter when that is what we are. */
const bunExecutable = (): string =>
  typeof (globalThis as { Bun?: unknown }).Bun !== "undefined" ? process.execPath : "bun";

export async function buildPlatform(
  platform: Platform,
  version: string,
  outDir: string,
  lock: Lock,
): Promise<Artifact> {
  const pin = lock.platforms[platform];
  if (!pin) throw new Error(`vendor/mise.lock.json has no pin for ${platform}`);

  await vendor(platform, lock);
  const platformDir = join(BUILD_DIR, platform);
  mkdirSync(platformDir, { recursive: true });

  // Recompressing 90MB per build is pure waste when the input has not moved —
  // but the marker has to be the *source* hash, or re-pinning mise would leave
  // yesterday's engine cached inside today's binary.
  const gzPath = join(platformDir, "mise.gz");
  const marker = join(platformDir, "mise.gz.source");
  const raw = readFileSync(vendoredMisePath(platform));
  const rawHash = sha256(raw);
  if (!existsSync(gzPath) || readMarker(marker) !== rawHash) {
    writeFileSync(gzPath, gzipSync(raw, { level: 9 }));
    writeFileSync(marker, rawHash);
  }

  const entry = join(platformDir, "entry.ts");
  writeFileSync(entry, entryPointSource(platformDir));

  const stage = join(platformDir, "stage");
  rmSync(stage, { recursive: true, force: true });
  mkdirSync(stage, { recursive: true });
  const binary = join(stage, "harv");

  execFileSync(
    bunExecutable(),
    [
      "build",
      "--compile",
      `--target=${bunTarget(platform)}`,
      `--define=__HARV_VERSION__="${version}"`,
      `--define=__HARV_MISE_VERSION__="${lock.version}"`,
      `--define=__HARV_MISE_SHA256__="${pin.sha256}"`,
      `--outfile=${binary}`,
      entry,
    ],
    { cwd: REPO_ROOT, stdio: "inherit" },
  );

  mkdirSync(outDir, { recursive: true });
  const tarball = join(outDir, `harv-${version}-${platform}.tar.gz`);
  execFileSync("tar", ["-czf", tarball, "-C", stage, "harv"], {
    // BSD tar otherwise smuggles AppleDouble `._harv` companions into the archive.
    env: { ...process.env, COPYFILE_DISABLE: "1" },
    stdio: "inherit",
  });

  return {
    platform,
    tarball,
    sha256: sha256(readFileSync(tarball)),
    binaryBytes: statSync(binary).size,
    tarballBytes: statSync(tarball).size,
  };
}

const readMarker = (path: string): string => {
  try {
    return readFileSync(path, "utf8").trim();
  } catch {
    return "";
  }
};

// ---------------------------------------------------------------------------
// Release-wide outputs
// ---------------------------------------------------------------------------

/** `sha256sum -c` / `shasum -a 256 -c` format, which install.sh and people both read. */
export const checksumsFile = (artifacts: Artifact[]): string =>
  artifacts.map((a) => `${a.sha256}  ${a.tarball.split("/").pop()}`).join("\n") + "\n";

/**
 * The Homebrew formula, generated rather than hand-maintained: it names four
 * URLs and four checksums that all change together on every release, which is
 * exactly the kind of thing a person gets wrong once and then ships.
 */
export function homebrewFormula(version: string, artifacts: Artifact[]): string {
  const by = (platform: Platform) => {
    const a = artifacts.find((x) => x.platform === platform);
    if (!a) throw new Error(`the formula needs a ${platform} artifact; build with --all`);
    return a;
  };
  const block = (platform: Platform, indent: string) =>
    `${indent}url "https://github.com/${REPO}/releases/download/v${version}/${by(platform).tarball.split("/").pop()}"\n` +
    `${indent}sha256 "${by(platform).sha256}"`;

  return `# Generated by scripts/build.ts for harv v${version}. Do not edit by hand.
class Harv < Formula
  desc "Harness virtual environments for Claude Code"
  homepage "https://github.com/${REPO}"
  version "${version}"

  on_macos do
    on_arm do
${block("darwin-arm64", "      ")}
    end
    on_intel do
${block("darwin-x64", "      ")}
    end
  end

  on_linux do
    on_arm do
${block("linux-arm64", "      ")}
    end
    on_intel do
${block("linux-x64", "      ")}
    end
  end

  def install
    bin.install "harv"
  end

  test do
    assert_match "harv #{version}", shell_output("#{bin}/harv --version")
  end
end
`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function flag(argv: string[], name: string): string | undefined {
  const at = argv.indexOf(`--${name}`);
  return at === -1 ? undefined : argv[at + 1];
}

function targets(argv: string[]): Platform[] {
  if (argv.includes("--all")) return [...PLATFORMS];
  const requested = flag(argv, "platform") ?? currentPlatform();
  if (!isPlatform(requested)) {
    throw new Error(`harv does not build for \`${requested}\`. Supported: ${PLATFORMS.join(", ")}.`);
  }
  return [requested];
}

const mb = (bytes: number) => `${(bytes / 1_048_576).toFixed(0)}MB`;

async function main(argv: string[]): Promise<number> {
  const version = (flag(argv, "version") ?? DEV_VERSION).replace(/^v/, "");
  const outDir = resolve(REPO_ROOT, flag(argv, "outdir") ?? "dist");
  const lock = readLock();

  const artifacts: Artifact[] = [];
  for (const platform of targets(argv)) {
    console.log(`\n=== harv ${version} — ${platform} (mise ${lock.version}) ===`);
    const artifact = await buildPlatform(platform, version, outDir, lock);
    artifacts.push(artifact);
    console.log(`    binary ${mb(artifact.binaryBytes)} → tarball ${mb(artifact.tarballBytes)}`);
  }

  writeFileSync(join(outDir, "checksums.txt"), checksumsFile(artifacts));
  if (artifacts.length === PLATFORMS.length && version !== DEV_VERSION) {
    writeFileSync(join(outDir, "harv.rb"), homebrewFormula(version, artifacts));
  }

  console.log(`\n${artifacts.length} artifact(s) in ${outDir}:`);
  for (const a of artifacts) console.log(`  ${a.sha256.slice(0, 12)}…  ${a.tarball.split("/").pop()}`);
  return 0;
}

const invokedDirectly =
  process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedDirectly) {
  process.exitCode = await main(process.argv.slice(2)).catch((err: Error) => {
    console.error(`build: ${err.message}`);
    return 1;
  });
}
