/**
 * `harv init`: turn a directory into a harvenv project.
 *
 * Three artifacts, and every one of them may already exist — init runs on a
 * greenfield directory and on a repo with years of `.gitignore` and a
 * hand-tuned `.claude/settings.json`, and has to be safe in both:
 *
 *   harvenv.toml           the Manifest, scaffolded valid and empty
 *   .gitignore             the generated and personal paths, appended
 *   .claude/settings.json  the Tripwire, merged into whatever is there
 *
 * Nothing is overwritten and nothing is reformatted beyond the merge itself, so
 * running init twice is a no-op and running it on an existing project only
 * tops up what is missing.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { loadManifest, MANIFEST_FILENAME } from "./manifest.ts";
import { MATERIALIZED_STATE_FILE } from "./materialize.ts";
import { hasTripwire, plantTripwire } from "./tripwire.ts";

/** Claude Code's committed project settings — the file the Tripwire lives in. */
export const PROJECT_SETTINGS_PATH = [".claude", "settings.json"];

/** A directory init cannot scaffold into. Always actionable, always user-facing. */
export class InitError extends Error {
  override name = "InitError";
}

/**
 * Generated by Sync, or personal to one person. Neither belongs in a commit:
 * materialized Components are absolute symlinks into a Store that only exists
 * on one machine, and an Overlay is by definition not the team baseline.
 */
export const GITIGNORE_ENTRIES = [
  ".claude/skills/",
  `.claude/${MATERIALIZED_STATE_FILE}`,
  ".claude/settings.local.json",
  "harvenv.local.toml",
];

const GITIGNORE_HEADER = "# harvenv — materialized Components and personal files, generated rather than authored";

/**
 * A Manifest that parses, declares nothing, and explains itself. The commented
 * examples are the documentation people actually read, so they carry the two
 * rules a first-time author will otherwise trip over: the key is the invocation
 * name (ADR 0008), and a declared setting is binding for the whole team
 * (ADR 0005).
 */
const MANIFEST_TEMPLATE = `# ${MANIFEST_FILENAME} — this project's Harvenv.
#
# \`harv claude\` composes a Claude Code session strictly from this file: the
# machine's user scope does not load, so a teammate who clones this repo gets
# the same harness. A bare \`claude\` here is not isolated, and says so.
#
# \`harv add <name> --git <coordinate>\` writes entries here and syncs them.

[skills]
# The key is the name the session answers to, and has to match the skill's own
# \`name:\` in its SKILL.md.
# brainstorming = { git = "https://github.com/obra/superpowers.git", ref = "v6.2.0", subdir = "skills/brainstorming" }

[settings]
# Settings declared here are binding for everyone on the project: a personal
# Overlay may add keys, never override one set here. Leave a key unset to keep
# it personal.
# model = "opus"
`;

export type StepAction = "created" | "updated" | "unchanged";

export interface InitStep {
  /** Project-relative, forward-slashed — what the user would type. */
  path: string;
  action: StepAction;
  detail: string;
}

export interface InitResult {
  root: string;
  steps: InitStep[];
}

interface PlannedStep extends InitStep {
  absolutePath: string;
  /** Absent when the step changes nothing. */
  contents?: string;
}

/**
 * Scaffold `root` as a harvenv project.
 *
 * Planned in full before a single byte is written, so a directory that cannot
 * be initialized — unreadable Manifest, settings.json that is not JSON — is
 * left exactly as it was rather than half-converted.
 */
export function init(root: string): InitResult {
  const steps = [planManifest(root), planGitignore(root), planSettings(root)];

  for (const step of steps) {
    if (step.contents === undefined) continue;
    mkdirSync(dirname(step.absolutePath), { recursive: true });
    writeFileSync(step.absolutePath, step.contents);
  }

  // The criterion is a *valid* Manifest, so the scaffold is read back through
  // the same loader `harv claude` uses rather than trusted because harv wrote it.
  loadManifest(join(root, MANIFEST_FILENAME));

  return { root, steps: steps.map(({ path, action, detail }) => ({ path, action, detail })) };
}

// ---------------------------------------------------------------------------
// The Manifest
// ---------------------------------------------------------------------------

function planManifest(root: string): PlannedStep {
  const absolutePath = join(root, MANIFEST_FILENAME);
  if (!existsSync(absolutePath)) {
    return {
      path: MANIFEST_FILENAME,
      absolutePath,
      action: "created",
      detail: "declares nothing yet",
      contents: MANIFEST_TEMPLATE,
    };
  }

  // Reading it proves the project is one harv can already work with, and
  // surfaces a broken Manifest here rather than at the next `harv claude`.
  const manifest = loadManifest(absolutePath);
  const declared = manifest.skills.length;
  return {
    path: MANIFEST_FILENAME,
    absolutePath,
    action: "unchanged",
    detail: declared === 0 ? "already present, declares nothing yet" : `already present, declares ${declared} skill(s)`,
  };
}

// ---------------------------------------------------------------------------
// The gitignore entries
// ---------------------------------------------------------------------------

function planGitignore(root: string): PlannedStep {
  const absolutePath = join(root, ".gitignore");
  const existing = read(absolutePath, ".gitignore");
  const missing = GITIGNORE_ENTRIES.filter((entry) => !ignored(existing ?? "", entry));

  if (missing.length === 0) {
    return { path: ".gitignore", absolutePath, action: "unchanged", detail: "all entries already present" };
  }

  const block = [...(existing?.includes(GITIGNORE_HEADER) ? [] : [GITIGNORE_HEADER]), ...missing].join("\n") + "\n";
  return {
    path: ".gitignore",
    absolutePath,
    action: existing === undefined ? "created" : "updated",
    detail: `${missing.length} entr${missing.length === 1 ? "y" : "ies"}: ${missing.join(", ")}`,
    contents: `${precedingBlock(existing)}${block}`,
  };
}

/** Whatever was there, ended and separated by one blank line — or nothing. */
function precedingBlock(existing: string | undefined): string {
  if (existing === undefined || existing.trim().length === 0) return "";
  const ended = existing.endsWith("\n") ? existing : `${existing}\n`;
  return ended.endsWith("\n\n") ? ended : `${ended}\n`;
}

/**
 * Whether the file already ignores this path.
 *
 * Compared with any trailing slash removed, because `.claude/skills` and
 * `.claude/skills/` ignore the same directory — a project that tidied the slash
 * away should not collect a duplicate on the next init. Comment lines do not
 * count: a commented-out entry ignores nothing.
 */
function ignored(gitignore: string, entry: string): boolean {
  const wanted = trimSlash(entry);
  return gitignore
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith("#"))
    .some((line) => trimSlash(line) === wanted);
}

const trimSlash = (value: string): string => value.replace(/\/+$/, "");

// ---------------------------------------------------------------------------
// The Tripwire
// ---------------------------------------------------------------------------

function planSettings(root: string): PlannedStep {
  const absolutePath = join(root, ...PROJECT_SETTINGS_PATH);
  const path = PROJECT_SETTINGS_PATH.join("/");
  const existing = read(absolutePath, path);

  if (existing === undefined) {
    const settings: Record<string, unknown> = {};
    plantTripwire(settings);
    return { path, absolutePath, action: "created", detail: "Tripwire planted", contents: serialize(settings, "  ") };
  }

  const settings = parseSettings(existing, path);
  if (hasTripwire(settings)) {
    return { path, absolutePath, action: "unchanged", detail: "Tripwire already planted" };
  }

  plantTripwire(settings);
  return {
    path,
    absolutePath,
    action: "updated",
    detail: "Tripwire merged in; nothing else changed",
    contents: serialize(settings, indentOf(existing)),
  };
}

function parseSettings(source: string, path: string): Record<string, unknown> {
  let parsed: unknown;
  try {
    parsed = JSON.parse(source);
  } catch (err) {
    throw new InitError(
      `${path} is not valid JSON (${(err as Error).message}). ` +
        `Fix it by hand — harv will not rewrite committed settings it cannot read.`,
    );
  }
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    const kind = parsed === null ? "null" : Array.isArray(parsed) ? "list" : typeof parsed;
    throw new InitError(`${path} must contain a JSON object, but it contains ${kind}.`);
  }
  return parsed as Record<string, unknown>;
}

/**
 * Reuse the file's own indentation. The merge already reformats the whole file;
 * matching what was there keeps the diff to the lines that actually changed.
 */
function indentOf(source: string): string {
  return /\n([ \t]+)\S/.exec(source)?.[1] ?? "  ";
}

const serialize = (value: unknown, indent: string): string => `${JSON.stringify(value, null, indent)}\n`;

/**
 * The file's contents, or `undefined` when it genuinely is not there.
 *
 * Only ENOENT counts as absent. Every other failure — a permission wall, a
 * directory standing where a file belongs — is reported rather than smoothed
 * over, because init plans a *create* for anything it reads as missing, and a
 * create is precisely what must not happen to a file that exists and could not
 * be read.
 */
function read(path: string, label: string): string | undefined {
  try {
    return readFileSync(path, "utf8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw new InitError(
      `Cannot read ${label}: ${(err as Error).message}. ` +
        `Fix it by hand — harv will not replace a file it was unable to read.`,
    );
  }
}
